#!/bin/sh

## hyphop ##

#= power off wakeup activation for power_key | IR/rc | wlan 

#echo 1 > /proc/sys/kernel/sysrq; echo b > /proc/sysrq-trigger

echo "
POWEROFF
" | tee /dev/ttyS0 /dev/tty0

echo 1 > /sys/class/mcu/poweroff || echo freeze > /sys/power/state



