#!/bin/bash

## hyphop ##

#= 

DIR="$(dirname $0)"
BN=$(basename $0)

cd "$DIR"
DP="$(realpath .)"

#N=${DP%/*}
N=${DP}
N=${N##*/}
M=${N%.krescue}

M="../../img/$M"
MP="$(realpath $M)"

mkdir -p $M
cd $M

DEVICE=VIM1
LINK=https://dl.khadas.com/Firmware/VIM1/Android/Pie/VIM1_Pie_V200317.7z

export LABEL=Android
export BUILDER=Khadas

case $0 in
*VIM3L)
DEVICE=VIM3L
LINK=https://dl.khadas.com/Firmware/VIM3L/Android/VIM3L_Pie_V201113.7z
;;
*VIM3L.workable)
DEVICE=VIM3L
LINK=https://dl.khadas.com/Firmware/VIM3L/Android/VIM3L_Pie_V191011.7z
LINK=https://dl.khadas.com/Firmware/VIM3L/Android/VIM3L_Pie_V191130.7z
LINK=https://dl.khadas.com/Firmware/VIM3L/Android/VIM3L_Pie_V200103.7z
LINK=https://dl.khadas.com/Firmware/VIM3L/Android/VIM3L_Pie_V200320.7z
;;
*VIM3)
DEVICE=VIM3
LINK=https://dl.khadas.com/Firmware/VIM3/Android/VIM3_Pie_V201112.7z
;;
*VIM2)
DEVICE=VIM2
LINK=https://dl.khadas.com/Firmware/VIM2/Android/Pie/VIM2_Pie_V200624.7z
;;
esac

INF=${LINK#*_}
INF=${INF%.*}

OUT=$DEVICE-$LABEL-$INF.raw.img.xz

echo "[i] $LINK to $OUT"

#UNPACK_ONLY=1 \
#NOCLEANUP=1 \

NOSINGLE=1 \
REWRITE=1 \
../../tools/aml2raw "$LINK" "$OUT"

