#!/bin/sh

## hyphop ##
D=$(dirname $0)

. $D/make_

VER=1.4.4
NAME=zstd
PKG=$NAME-$VER.tar.gz

echo "[i] make $PKG">&2

../download https://github.com/facebook/zstd/releases/download/v$VER/$NAME-$VER.tar.gz $PKG $DL

cd $DL

D=${PKG%.tar.*}

[ -d $D ] || \
    tar -xf $PKG

cd $D

make && \
    make install PREFIX="$PRE2"