#!/bin/sh

## hyphop ##

#= make xz

D=$(dirname $0)

. $D/make_

PKG=xz-5.2.4.tar.gz

echo "[i] make $PKG">&2

../download https://tukaani.org/xz/$PKG $PKG $DL

cd $DL

D=${PKG%.tar.*}

[ -d "$D" ] || \
    tar -xf $PKG

cd $D

./configure --prefix="$PRE2" && \
    make && \
	make install
