LABEL=COREELEC
VER=${VER:-9.2.2}
LINK0=https://github.com/CoreELEC/CoreELEC/releases/tag/$VER
NAME=VIM3x.COREELEC.$VER
IMG_PRE=CoreELEC-Amlogic-ng.arm-
IMG=$IMG_PRE$VER.tar
BASE=https://github.com/CoreELEC/CoreELEC/releases
LINK=$BASE/download/$VER/$IMG
FIX_GREEN=1
TYPE=NG
MATCH="BOARD=VIM3 BOARD=VIM3L"
VARS="BOARD=VIM3 VIM3L"
