#!/bin/sh

## hyphop ##

#= make kresq 

DIR="$(dirname $0)"
DP="$(realpath $DIR)"
#N=${DP%/*}
N=${DP}
N=${N##*/}
M=${N%.krescue}
M="../../img/$M"
MP="$(realpath $M)"

CMP_LEVEL="-22 -T2"

LABEL=MANJARO

echo "[i] started $N -> $M">&2
mkdir -p "$M"

cd $M

#https://yadi.sk/d/rYzimbOHPxI36w

IMG=Manjaro-ARM-kde-plasma-vim3-20.02.img.xz
IMG=Manjaro-ARM-xfce-vim3-20.02.img.xz
IMG=Manjaro-ARM-kde-plasma-vim1-20.02.img.xz

LINK='https://s356myt.storage.yandex.net/rdisk/57b25ccd3db39f6eda51f01c5e2770a8910dc22a5536a70abc314efdc010be3c/5e50c9ca/y4OIVLHNyzX0NTbW48Ex-u_ma7OnnhDBz1f4lTRP0MhnaOv_GE-eoy_1_-pGqyuvTTiMbDKRUBTo6R-Y0EpCHQ==?uid=0&filename=Manjaro-ARM-kde-plasma-vim3-20.02.img.xz&disposition=attachment&hash=f5TMIKGbxCKM0b3V81UrhMpLEPU23uB4vZZzcoARbnLGX/qr8onHljlUzP/N%2BHUVq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=application%2Fx-xz&owner_uid=925285346&fsize=968259664&hid=097bee90e5362cff6ad12a92352ad14f&media_type=unknown&tknv=v2&rtoken=8ba5oEQ0o4KS&force_default=no&ycrid=na-4259c5c771b37ddead77fa9a1d3c5480-downloader11e&ts=59f243b0e8680&s=c052489ace1740882748dabafc4427deab259cc6fa862fb5dac938357f016e3e&pb=U2FsdGVkX18vWcJXZxvyk00Uil7PSp7YOSA9LZCaCNbDSqwj8lCLl2wV9ct6uF6hupR3aw7ux1UDfPLP_O6roUlUS-ADf4yV6Of0KxQuyEs'
LINK='https://s53iva.storage.yandex.net/rdisk/28a34cbddb86b7f704e39dc611caab8b3b99332b51d48c2a91b60455b07bf1b4/5e534dc6/y4OIVLHNyzX0NTbW48Ex-llZELz9YBNkLZHhbvGvfluHMFe-xKVGF2GEjD4BT7gwFvOb7hXdV8w9URa43_KioQ==?uid=0&filename=Manjaro-ARM-xfce-vim3-20.02.img.xz&disposition=attachment&hash=s4mEUmIHnbxnMx3oC6FLm4maWvgchiyxuKEc3pRfqkeuo0s%2BYS5/OZYmApTHorD2q/J6bpmRyOJonT3VoXnDag%3D%3D%3A/Manjaro-ARM-xfce-vim3-20.02.img.xz&limit=0&content_type=application%2Fx-xz&owner_uid=925285346&fsize=758090256&hid=da24284422039af31d54e08cb9177d90&media_type=unknown&tknv=v2&rtoken=7Bqdx0ZtUHyz&force_default=no&ycrid=na-714bcc7b365eabcc7eae120af7d59e93-downloader23h&ts=59f4a9d7a7d80&s=e6f4a44bb77d46fe7d858f6a37970d8ed67f50469e23aced5d5f5705ff3695c0&pb=U2FsdGVkX1_rbOTnPRgC4K7SkwCLSLtFroqVhtOU1N4Qds0MLs2zHHobf4edCIJh1OknlA577RX69LJ0UlABHXFQgyiCA4sFQCazuyaBseA'
LINK='https://s467man.storage.yandex.net/rdisk/d7e3ffd706518bd1d35564a419306dcd5b5359385ab17ac7990e37bf91b2e06c/5e53d5b8/y4OIVLHNyzX0NTbW48Ex-nSusWbE-_oijgPp4J_DVPimoKxqh3f-jb9oYHe0p1WZRWBr7ymbBu3MkAF-qUI-BQ==?uid=0&filename=Manjaro-ARM-kde-plasma-vim1-20.02.img.xz&disposition=attachment&hash=s4mEUmIHnbxnMx3oC6FLm4maWvgchiyxuKEc3pRfqkeuo0s%2BYS5/OZYmApTHorD2q/J6bpmRyOJonT3VoXnDag%3D%3D%3A/Manjaro-ARM-kde-plasma-vim1-20.02.img.xz&limit=0&content_type=application%2Fx-xz&owner_uid=925285346&fsize=966911888&hid=5727c89d885e83e87977d3c716c48ed4&media_type=unknown&tknv=v2&rtoken=YFSqqZ8EkeO6&force_default=no&ycrid=na-5732e6d99a2803f89983ba4d109399a4-downloader12f&ts=59f52b7d6de00&s=57497e9589c16cae6b3421e792d9957db9787f82dc4cdd27c2d069f42325337a&pb=U2FsdGVkX19Qla-Z-g_vsYQzb9glaXoBVZgWdkNnmVMDQzQvLC2V4gMZHUQRgoJXpUZh2d2YF08TZ8ssdXMgQmtk2fnk_aJKClna-LXMmes'

DL="dl"
CNF_=krescue.image.conf
CNF=.$CNF_
R=README.txt
META=".meta"
BOOT="BOOT"
ROOT=.
ROOT=ROOT
ROOTFS=$ROOT/rootfs.img

CMD(){
    echo "# $@">&2
    $@
}

FAIL(){
    echo "[e] $@">&2
    exit 1
}

[ "$z7r" ] || \
z7r="$(which 7zr)"
[ $? = 0 ] || FAIL 7zr not found! plz install it

[ "$mcopy" ] || \
mcopy="$(which mcopy)"
[ $? = 0 ] || FAIL mcopy not found ! plz install mtools

[ "$sfdisk" ] || \
sfdisk="$(which sfdisk)"
[ $? = 0 ] || FAIL sfdisk not found ! plz install it

[ "$xz" ] || \
xz="$(which pixz)"
[ $? = 0 ] || \
xz="$(which xz)"
[ $? = 0 ] || FAIL xz not found ! plz install xz or pixz

[ -f $R ] || {
    echo "[i] create README: $R">&2
    echo "$IMG
$LINK
" > $R
}

#[ -f "../$CNF" ] || {
    echo "[i] copy kresq config from template"
    CMD cp $DP/$CNF_ $CNF
    CMD rsync -av --inplace  $DP/$CNF_ $CNF
#}

[ -d $META ] || mkdir -p $META
[ -d $DL ] || mkdir -p $DL

../../scripts/download "$LINK" "$IMG" $DL || FAIL download

IMG_="$DL/$IMG"
IMG2="$DL/${IMG%.*}"

[ -f "$IMG2" ] || {
    echo "[i] unpack $IMG_">&2
#    echo "[i] 7zr -so e $IMG_ > $IMG2">&2
#    $z7r -so e "$IMG_" > $IMG2 || DIE
    echo "[i] xz -dc $IMG_ > $IMG2">&2
    $xz -dc < "$IMG_" > $IMG2 || FAIL extract
}


[ -s "$IMG2" ] && {

echo "[i] extract $IMG2">&2

file $IMG2 | grep partition || {
    echo "[e] wrong disk image IMG$">&2
    exit 1 
}

$sfdisk $IMG2 --dump

S1="$($sfdisk $IMG2 --dump | grep type=c)"
S1=${S1#*start=}
S1=${S1%%,*}
S1=$(echo $S1)

echo mtools_skip_check=1 > ~/.mtoolsrc

[ -d  $BOOT.org ] || {
echo "[i] copy boot partition">&2
$mcopy -sbpmi $IMG2@@$((512*S1)) :: $BOOT.org || FAIL extract boot partition to $BOOT.org
}

S2="$($sfdisk $IMG2 --dump | grep type=83)"
S2=${S2#*start=}
S2=${S2%%,*}
S2=$(echo $S2)

[ -d "$ROOT" ] || mkdir -p $ROOT

[ -f $ROOTFS ] || {
echo "[i] extract rootfs => $ROOTFS">&2
dd if=$IMG2 skip=$((S2)) of=$ROOTFS
fsck.ext4 -f $ROOTFS || FAIL rootfs image check
#resize2fs -M $ROOTFS
}

ls -l1

truncate -s0 $IMG2

}

for p in $ROOTFS; do
[ -s $p ] || continue
[ -f $p ] || continue
[ -f $p.zstd ] && {
[ -f $p.packed ] || FAIL broken $p.zstd
continue
}
echo "[i] rootfs image compress">&2

CMD ../../scripts/zstde $CMP_LEVEL $p $p.zstd || FAIL compress
echo $p.zstd > $p.packed
CMD truncate -s0 $p
done


echo "[i] prepare bootloaders">&2

BASE=https://github.com/hyphop/khadas-uboot-spi/releases/download/mainline-test/

for VIM in VIM1 VIM2 VIM3 VIM3L; do
    D=$BOOT.$VIM
    [ -d $D ] || mkdir -p $D
    UBOOT=u-boot.$VIM.sd.bin
    ../../scripts/download $BASE$UBOOT $UBOOT $D
done

[ -d "$BOOT.org" ] && {

echo "[i] prepare boot">&2

CMD cp -a $DP/$BOOT .

. $BOOT/boot.cfg

CMD mkdir -p $BOOT/$UBOOT_DTB_DIR

cp $BOOT.org/$UBOOT_KERNEL    $BOOT
cp $BOOT.org/$UBOOT_UINITRD   $BOOT

cp $BOOT.org/$UBOOT_DTB_VIM1  $BOOT/$UBOOT_DTB_VIM1
cp $BOOT.org/$UBOOT_DTB_VIM2  $BOOT/$UBOOT_DTB_VIM2
cp $BOOT.org/$UBOOT_DTB_VIM3  $BOOT/$UBOOT_DTB_VIM3
cp $BOOT.org/$UBOOT_DTB_VIM3L $BOOT/$UBOOT_DTB_VIM3L

echo $LABEL > $BOOT/LABEL
echo $LABEL > $BOOT/$LABEL.label

rm -rf $BOOT.org

ls -l1 $BOOT

}

[ -d "$BOOT" ] || FAIL $BOOT dir was removed

echo "[i] project is ready: $MP">&2

echo "[i] make image">&2
CMD make_image

