#!/bin/sh

## hyphop ##

#= make kresq 

DIR="$(dirname $0)"
DP="$(realpath $DIR)"
#N=${DP%/*}
N=${DP}
N=${N##*/}
M=${N%.krescue}
M="../../img/$M"
MP="$(realpath $M)"

echo "[i] started $N -> $M">&2
mkdir -p "$M"

cd $M

IMG=SC_VIM1_DEBUG_ATV-v2.0-20200130.7z
LINK='https://mega.nz/#!ItRCgIjS!G6NgnVhAcGj-5DY_RrDmSf92lkXjLhLbyPD4UnsGcCg'
#LINK='https://mega.nz/#!Wo8jhILB!WJAoj87K3hvpmVafUUgvMr7kDZRoSMdXllB-AMjixDc'

DL="dl"
TPL=boot.atv.v2.tar.gz
CNF_=krescue.image.conf
CNF=.$CNF_
R=README.txt
META=".meta"
OUT=".boot"

CMD(){
    echo "# $@">&2
    $@
}

[ -f $R ] || {
    echo "[i] create README: $R">&2
    echo "$IMG
$LINK
" > $R
}


[ -f "../$CNF" ] || {
    echo "[i] copy kresq config from template"
    CMD cp $DP/$CNF_ $CNF
}

[ -d $META ] || mkdir -p $META
[ -d $DL ] || mkdir -p $DL

DIE(){
    echo "[e] DIE">&2
    exit 1
}

GET(){
    O_=$2
    D_=$3
    echo "[i] DOWNLOAD $1 => $O_ DIR $D_">&2

    T_=/tmp/dl.head
    P_=$(pwd)

    cd $D_

    [ -f "$O_.md5sum" ] && {
	echo "[w] already downloaded">&2
	cd $P_
	return 0
    }

    case $1 in
	*//mega*)
	megadl --print-names "$1" | tee $T_
	o_=$(tail -1 "$T_")
	[ "$o_" = "$O_" ] || \
	CMD mv "$o_" "$O_"
	;;
	*//*)
	curl -jkL "$1" -O "$O_"
	;;
    esac

    [ "$?" = "0" ] && {
	md5sum "$O_" > "$O_.md5sum"
	cd $P_
	return 0
    }

    cd $P_

}

GET "$LINK" "$IMG" $DL || DIE

IMG_="$DL/$IMG"
IMG2="$DL/${IMG%.7z}.img"

echo "[i] $IMG2"

[ -f "$IMG2" ] || {
    echo "[i] 7zr -so e $IMG_ > $IMG2">&2
    7zr -so e "$IMG_" > $IMG2 || DIE
}

[ -d "$OUT" ] || {
    CMD tar -xf $DP/$TPL || DIE
    CMD mv boot $OUT
}

[ -f $OUT/aml_sdc_burn.ini -a -f $OUT/unpacked ] || {
CMD aml_image_v2_packer -d $IMG2 "$OUT" || DIE

date > $OUT/unpacked

[ -s $IMG2 ] && printf "" > $IMG2

for R in aml_sdc_burn.ini  DDR.USB  image.cfg  platform.conf  UBOOT.USB; do
    CMD rm "$OUT/$R"
done

../../scripts/sparseimg2img $OUT

}

echo "[i] project is ready: $MP">&2

CMD make_image

