#!/bin/sh

## hyphop ##

#= xze - advanced xz + suitable for mt decompression & padding & meta

USAGE() { echo '
    xze - advanced xz + suitable for mt decompression & padding

USAGE

    xze [ARGS] FILE
    
    -T#thread
    -B#blocksize in M

META USAGE

    ./xze rootfs_stage.sh -M INFO="any strings" VAR=val

META USAGE EXAMPLE (Krescue images)

    ./xze FreeBSD-aarch64-13.0-Khadas-EDGE-V-361468M-20200528.img \
	-M \
	\##KRESCUE-META## \
	LABEL=FreeBSD \
	IMAGE="FreeBSD-aarch64-13.0-Khadas-EDGE-V-361468M-20200528" \
	BUILDER=Serega \
	DATE="$(date)" \
	MATCH=board=EDGE \
	LINK=http://dev.kubsu.ru/images/ \
	DURATION=60 \
	DESC="FreeBSD 13.0 for Khadas EDGE board aarch64...." \
	\##KRESCUE_META## \
	\##KRESCUE##END

READ META

    tail -c4096 FILE.xz | xz -dc

'
exit 
}

[ "$xz" ] || xz=$(which xz)
[ $? = 0 ] || {
    echo "[e] plz install xz">&2
    echo " sudo apt-get install xz-utils">&2
    exit 1
}

echo "[i] $xz">&2

$xz --help | grep -q threads= || {
    echo "[i] plz install last xz with MT support">&2
    exit 1
}


IN=
OPTS=

[ $# = 0 ] && USAGE

T=4      # threads
B=90     # in MEGS

META=
for a in $@; do
    shift
    case $a in
	-m)
	META=1
	break
	;;
	-M)
	META=2
	break
	;;
	-T*)
	T=${a#-T}
	continue
	;;
	-B*)
	B=${a#-B}
	continue
	;;
	*)
	[ -f "$a" ] && {
	    [ "$IN" ] || IN="$a"
	    continue
	}
	OPTS="$OPTS $a"
	;;
    esac
done

[ "$IN" ] || USAGE

OUT="$IN.xz"


BS=4096 # block size

for S1 in $(du -b "$IN");do
break
done

S14=$((S1/T))
[ $S14 -lt $B ] && B=$S14

B="${B}M"

ARGS="$xz -T$T --block-size $B -k -c $OPTS "$IN""

echo "[i] xze compress $IN ($S1 bytes) > $OUT">&2
echo "# $ARGS">&2

$ARGS > "$OUT"

S=
S2=
PAD(){
for S in $(du -b "$1"); do 
break 
done
S2=$((S/BS*BS))
[ $S2 -lt $S ] && S2=$((S2+BS))
SD=$((S2-S))
[ "$2" ] && \
printf %${SD}s "$2" >> "$1"
[ "$2" ] || \
dd if=/dev/zero bs=$SD count=1 2>/dev/null >> "$1"
echo "[i] compressed $S2 < $S1">&2
echo $S2
}

PAD "$OUT"

XZS=$($xz -l "$OUT")
echo "[i] XZ info
$XZS">&2

[ "$META" ] && {
    echo "[i] add meta block">&2

    meta="/tmp/meta.$$"
    touch $meta

    for m in "$@"; do
    M="$m"
    [ "$META" = "2" ] && M=$(echo "$m" | sed s/=/:\ /)
#   echo "[i] add meta $M">&2
    [ -s $meta ] || {
    (
    echo "##META_FILE##"
    echo "FILE: $OUT"
    echo "UNPACKED_SIZE: $S1"
    echo "PACKED_SIZE: $S2"
    echo "FILE_SIZE: $((S2+BS))"
    echo "##META-FILE##"
    ) >> $meta
    }
    echo "$M" >> $meta
    done

    [ -s $meta ] && {
    cat $meta >&2
#    PAD $meta " "
    }
    $xz $meta
    PAD $meta.xz
    cat $meta.xz >> "$OUT"
    rm $meta.xz

}
#echo "[i] pad +$SD">&2
